/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jpprof;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.*;
import java.time.Duration;

public class LibraryTest {
    @Test
    public void TestPProf() throws Exception {
        File file = File.createTempFile("abc", ".tmp");
        try (FileOutputStream fos = new FileOutputStream(file)) {
            CPUProfiler.start(Duration.ofSeconds(5), fos);
        }
    }

    @Test
    public void TestBuildCommand() {
        // See
        // https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/arguments.cpp#L52-L111
        String out = CPUProfiler.buildStartCommand("foo");
        assertEquals("start,event=cpu,interval=10000000,file=foo,jfr", out);
    }
}
