/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jpprof;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.File;
import java.io.FileOutputStream;
import java.util.zip.GZIPOutputStream;

import one.jfr.JfrReader;
import one.profiler.*;

public class LibraryTest {
    @Test
    public void TestJFR() {

    }
}
