/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jpprof;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.*;
import java.time.Duration;

public class LibraryTest {
    @Test
    public void TestPProf() throws Exception {
        File file = File.createTempFile("abc", ".tmp");
        try (FileOutputStream fos = new FileOutputStream(file)) {
            CPUProfiler.start(Duration.ofSeconds(5), fos);
        }
    }
}
